"""facts, fact_sources, business_summaries, pages/chunks metadata

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04 05:36:58.784592

plan/07-knowledge-quality.md §5.2/§8 (DEC-38/39/40): adds the facts library schema
(`facts`, `fact_sources`, `business_summaries`) and the organize-step metadata columns
on `pages` (page_type, location_id, language, retrievable, duplicate_of, published_at,
organized_hash, extracted_hash, extractor_version, chrome_markdown) and `chunks`
(fact_id, location_id, and 'fact' added to the `kind` enum). Schema only — extraction,
merge and summary generation (`app/ingest/facts.py`/`merge.py`/`summary.py`) are a later
milestone (OPEN-20); `app/ingest/organize.py` (this change) only writes the `pages`
columns and updates `locations`.

`chrome_markdown` is one column beyond what the plan's schema sketch lists for `pages`
-- the sketch doesn't carry it explicitly, but site-chrome dedup (DEC-40 K2) needs each
page's own chrome text available on a later standalone `--only organize` re-run, and raw
HTML isn't stored (DEC-09), so it has to live somewhere once crawl-time. Documented here
rather than silently added.

Autogenerated by `alembic revision --autogenerate` from app/db/models.py, then hand-
edited to add the `chunks.kind`/`chunks.source` CHECK constraint changes (autogenerate
doesn't diff CHECK constraints) and this docstring.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_summaries',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('one_liner', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('highlights', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('guest_themes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('tone', sa.Text(), nullable=True),
    sa.Column('source_page_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_summaries_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id', name=op.f('pk_business_summaries'))
    )
    op.create_table('facts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('attribute', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('fact_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='candidate', nullable=False),
    sa.Column('origin', sa.Text(), server_default='crawl', nullable=False),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id', 'location_id'], ['locations.business_id', 'locations.id'], name=op.f('fk_facts_business_id_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_facts_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facts')),
    sa.UniqueConstraint('business_id', 'id', name=op.f('uq_facts_business_id_id'))
    )
    op.create_index(op.f('ix_facts_business_id'), 'facts', ['business_id'], unique=False)
    op.create_index(op.f('ix_facts_location_id'), 'facts', ['location_id'], unique=False)
    op.create_index('uq_facts_business_id_fact_key_active', 'facts', ['business_id', 'fact_key'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('fact_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('page_hash', sa.Text(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id', 'fact_id'], ['facts.business_id', 'facts.id'], name=op.f('fk_fact_sources_business_id_fact_id_facts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id', 'page_id'], ['pages.business_id', 'pages.id'], name=op.f('fk_fact_sources_business_id_page_id_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_fact_sources_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_sources'))
    )
    op.create_index(op.f('ix_fact_sources_business_id'), 'fact_sources', ['business_id'], unique=False)
    op.create_index(op.f('ix_fact_sources_fact_id'), 'fact_sources', ['fact_id'], unique=False)
    op.create_index(op.f('ix_fact_sources_page_id'), 'fact_sources', ['page_id'], unique=False)
    op.add_column('chunks', sa.Column('fact_id', sa.UUID(), nullable=True))
    op.add_column('chunks', sa.Column('location_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_chunks_fact_id'), 'chunks', ['fact_id'], unique=False)
    op.create_index(op.f('ix_chunks_location_id'), 'chunks', ['location_id'], unique=False)
    op.create_foreign_key(op.f('fk_chunks_business_id_location_id_locations'), 'chunks', 'locations', ['business_id', 'location_id'], ['business_id', 'id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_chunks_business_id_fact_id_facts'), 'chunks', 'facts', ['business_id', 'fact_id'], ['business_id', 'id'], ondelete='CASCADE')
    # Not autogenerated (alembic doesn't diff CHECK constraints): widen chunks.kind to
    # include 'fact', and chunks.source so a fact-kind row requires fact_id (and
    # forbids page_id/custom_reply_id), matching the other two kinds' shape.
    op.drop_constraint(op.f('ck_chunks_kind'), 'chunks', type_='check')
    op.drop_constraint(op.f('ck_chunks_source'), 'chunks', type_='check')
    op.create_check_constraint(op.f('ck_chunks_kind'), 'chunks', "kind IN ('scraped', 'custom_reply', 'fact')")
    op.create_check_constraint(
        op.f('ck_chunks_source'), 'chunks',
        "(kind = 'scraped' AND page_id IS NOT NULL AND custom_reply_id IS NULL AND fact_id IS NULL)"
        " OR (kind = 'custom_reply' AND custom_reply_id IS NOT NULL AND page_id IS NULL AND fact_id IS NULL)"
        " OR (kind = 'fact' AND fact_id IS NOT NULL AND page_id IS NULL AND custom_reply_id IS NULL)",
    )
    op.add_column('pages', sa.Column('chrome_markdown', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('page_type', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('location_id', sa.UUID(), nullable=True))
    op.add_column('pages', sa.Column('language', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('retrievable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pages', sa.Column('duplicate_of', sa.UUID(), nullable=True))
    op.add_column('pages', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pages', sa.Column('organized_hash', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('extracted_hash', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('extractor_version', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_pages_business_id_duplicate_of_pages'), 'pages', 'pages', ['business_id', 'duplicate_of'], ['business_id', 'id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_pages_business_id_location_id_locations'), 'pages', 'locations', ['business_id', 'location_id'], ['business_id', 'id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_pages_business_id_location_id_locations'), 'pages', type_='foreignkey')
    op.drop_constraint(op.f('fk_pages_business_id_duplicate_of_pages'), 'pages', type_='foreignkey')
    op.drop_column('pages', 'extractor_version')
    op.drop_column('pages', 'extracted_hash')
    op.drop_column('pages', 'organized_hash')
    op.drop_column('pages', 'published_at')
    op.drop_column('pages', 'duplicate_of')
    op.drop_column('pages', 'retrievable')
    op.drop_column('pages', 'language')
    op.drop_column('pages', 'location_id')
    op.drop_column('pages', 'page_type')
    op.drop_column('pages', 'chrome_markdown')
    op.drop_constraint(op.f('fk_chunks_business_id_fact_id_facts'), 'chunks', type_='foreignkey')
    op.drop_constraint(op.f('fk_chunks_business_id_location_id_locations'), 'chunks', type_='foreignkey')
    op.drop_constraint(op.f('ck_chunks_source'), 'chunks', type_='check')
    op.drop_constraint(op.f('ck_chunks_kind'), 'chunks', type_='check')
    op.create_check_constraint(op.f('ck_chunks_kind'), 'chunks', "kind IN ('scraped', 'custom_reply')")
    op.create_check_constraint(
        op.f('ck_chunks_source'), 'chunks',
        "(kind = 'scraped' AND page_id IS NOT NULL AND custom_reply_id IS NULL)"
        " OR (kind = 'custom_reply' AND custom_reply_id IS NOT NULL AND page_id IS NULL)",
    )
    op.drop_index(op.f('ix_chunks_location_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_fact_id'), table_name='chunks')
    op.drop_column('chunks', 'location_id')
    op.drop_column('chunks', 'fact_id')
    op.drop_index(op.f('ix_fact_sources_page_id'), table_name='fact_sources')
    op.drop_index(op.f('ix_fact_sources_fact_id'), table_name='fact_sources')
    op.drop_index(op.f('ix_fact_sources_business_id'), table_name='fact_sources')
    op.drop_table('fact_sources')
    op.drop_index('uq_facts_business_id_fact_key_active', table_name='facts', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_facts_location_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_business_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_table('business_summaries')
    # ### end Alembic commands ###
