"""pages.testimonials

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 05:37:33.976087

plan/07-knowledge-quality.md §6/§9 (milestone-1 review finding "testimonials
discarded"): `organize.cut_testimonials()` cuts review blocks out of a page before
chunking (K6); this column keeps them for `summary.py`'s guest themes instead of
throwing them away. Written by `app/ingest/run.py:_rechunk_page`; ORGANIZER_VERSION is
bumped to 2 in the same change so the next crawl fills it for pages already stored.

Autogenerated by `alembic revision --autogenerate` from app/db/models.py.
"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — referenced by autogenerated vector columns
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('testimonials', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'testimonials')
    # ### end Alembic commands ###
