"""conversations.call_sid

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 05:42:42.317031

Stage 1 step 4, Twilio part (plan/03-voice-channel.md): Twilio calls (modes A/B) store
their CallSid on the conversation, so POST /twilio/status can set `ended_at` for a call
whose WebSocket never closed cleanly (V19) and later run the summary (DEC-24). Unique:
one Twilio call = one media stream = one conversation. NULL for browser/chat
conversations (Postgres UNIQUE allows many NULLs). Autogenerated, unchanged.
"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401 — referenced by autogenerated vector columns
import sqlalchemy as sa
from alembic import op


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('call_sid', sa.Text(), nullable=True))
    op.create_unique_constraint(op.f('uq_conversations_call_sid'), 'conversations', ['call_sid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_conversations_call_sid'), 'conversations', type_='unique')
    op.drop_column('conversations', 'call_sid')
    # ### end Alembic commands ###
